services:
  trilium:
    image: triliumnext/notes:latest
    container_name: trilium
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=notes
      - tsdproxy.container_port=8080
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - '46548:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - /var/appdata/trillium-next:/home/node/trilium-data:z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
