---

- name: Init Users
  hosts: init
  # remote_user: core
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

    - name: Set system timezone to America/New_York
      community.general.timezone:
        name: America/New_York

    - name: Create users
      become: true
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        home: "/home/{{ item.name }}"
        group: "{{ item.name }}"
        state: present
        expires: -1
      loop: "{{ service_users }}"

    - name: Create Groups
      become: true
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ service_users }}"

    # - name: Correct ownership of user home directories
    #   become: true
    #   ansible.builtin.file:
    #     path: "/var/home/{{ item.name }}"
    #     owner: "{{ item.uid }}"
    #     group: "{{ item.gid }}"
    #     mode: '0700'
    #     recurse: true
    #   loop: "{{ service_users }}"

    - name: Create User Folders
      become: true
      ansible.builtin.file:
        dest: "/var/home/{{ item.name }}/.config/containers/systemd"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0777'
      loop: "{{ service_users }}"

    - name: Create Appdata Folders
      become: true
      ansible.builtin.file:
        dest: "/var/home/{{ item.name }}/appdata"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0740'
      loop: "{{ service_users }}"

    - name: Set authorized key for service users
      become: true
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.authorized_key }}"
      loop: "{{ service_users }}"
      when: item.authorized_key is defined and item.authorized_key != ''

    - name: Ensure User SubUID
      become: true
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: "{{ item.name }}:{{ item.uid * 1000 }}:65536"
        create: true
        state: present
        owner: root
        group: root
        mode: '0777'
      loop: "{{ service_users }}"
      when: item.linger

    - name: Ensure User SubGID
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/subgid
        line: "{{ item.name }}:{{ item.uid * 1000 }}:65536"
        create: true
        state: present
        owner: root
        group: root
        mode: '0777'
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Linger for service users
      become: true
      ansible.builtin.command:
        argv:
          - /usr/bin/loginctl
          - enable-linger
          - "{{ item.name }}"
        creates: "/var/lib/systemd/linger/{{ item.name }}"
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Podman socket for lingering service users
      become: true
      become_user: "{{ item.name }}"
      ansible.builtin.systemd_service:
        scope: user
        name: podman.socket
        enabled: true
      loop: "{{ service_users }}"
      when: item.linger

    - name: Disable Podman service for lingering service users
      become: true
      become_user: "{{ item.name }}"
      ansible.builtin.systemd_service:
        scope: user
        name: podman.service
        enabled: false
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Podman auto update timer for lingering service users
      become: true
      become_user: "{{ item.name }}"
      ansible.builtin.systemd_service:
        scope: user
        name: podman-auto-update.timer
        enabled: true
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Podman restart.service for lingering service users
      become: true
      become_user: "{{ item.name }}"
      ansible.builtin.systemd_service:
        scope: user
        name: podman-restart.service
        enabled: true
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Podman clean-transient.service for lingering service users
      become: true
      become_user: "{{ item.name }}"
      ansible.builtin.systemd_service:
        scope: user
        name: podman-clean-transient.service
        enabled: true
      loop: "{{ service_users }}"
      when: item.linger

    - name: Enable Podman auto update timer for system
      become: true
      ansible.builtin.systemd_service:
        name: podman-auto-update.timer
        enabled: true

    - name: Enable Podman restart.service for system
      become: true
      ansible.builtin.systemd_service:
        name: podman-restart.service
        enabled: true

    - name: Enable Podman clean-transient.service for system
      become: true
      ansible.builtin.systemd_service:
        name: podman-clean-transient.service
        enabled: true

    - name: Add Ansible user to wheel group
      become: true
      ansible.builtin.user:
        append: true
        name: ansible
        groups:
          - wheel

    - name: Add Virt user to libvirt group
      become: true
      ansible.builtin.user:
        append: true
        name: virt
        groups:
          - libvirt
      when: "'hci' in group_names"

    - name: Ensure python venv for ansible
      become: true
      become_user: ansible
      ansible.builtin.command:
        argv:
          - uv
          - venv
          - /home/ansible/venv
        creates: /home/ansible/venv

- name: Core Init
  hosts: init
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Setup baseline packages and repositories for non-bootc systems
      when: "'package_managed' in group_names"
      ansible.builtin.include_tasks: tasks/init/baseline_packages.yaml

    - name: Setup Systemd Credentials
      become: true
      ansible.builtin.command:
        argv:
          - systemd-creds
          - setup
        creates: /var/lib/systemd/credential.secret

    - name: Set Hostname
      ansible.builtin.copy:
        dest: /etc/hostname
        content: "{{ inventory_hostname }}"
        owner: root
        group: root
        mode: '755'

    - name: Setup Tailscale
      vars:
        ts_domain: "{{ inventory_hostname }}.{{ secrets.ts_handle }}.ts.net"
        cert_renewal_interval: weekly
      block:
        - name: Ensure Tailscaled
          ansible.builtin.systemd_service:
            name: tailscaled.service
            enabled: true
            state: "started"

        - name: Allow Proxy User to create Certs
          ansible.builtin.lineinfile:
            path: /etc/default/tailscaled
            line: "TS_PERMIT_CERT_UID=2600"
            state: present
            create: true
            group: root
            mode: '644'

        - name: Tailscale up
          ansible.builtin.command:
            argv:
              - tailscale
              - up
              - --reset
              - --accept-dns
              - --ssh=false
              - --accept-risk=lose-ssh
              - --auth-key={{ secrets.tailscale_authkey }}
              - --hostname={{ inventory_hostname }}
          register: tailscale_up
          changed_when: tailscale_up.rc == 0

        - name: Ensure Tailscale ssl directory
          ansible.builtin.file:
            path: /etc/ssl/certs/tailscale/
            state: directory
            owner: root
            group: proxy
            mode: '775'

        - name: Template Cert Gen Service
          become: true
          ansible.builtin.template:
            dest: /etc/systemd/system/tailscale_gen_cert.service
            src: templates/units/tailscale_gen_cert/tailscale_gen_cert.service.j2
            owner: root
            group: root
            mode: '600'
            force: true

        - name: Template Cert Gen Timer
          become: true
          ansible.builtin.template:
            dest: /etc/systemd/system/tailscale_gen_cert.timer
            src: templates/units/tailscale_gen_cert/tailscale_gen_cert.timer.j2
            owner: root
            group: root
            mode: '600'
            force: true

        - name: Generate Certs
          ansible.builtin.systemd_service:
            name: tailscale_gen_cert.service
            daemon_reload: true
            state: "started"

        - name: Activate Cert Renewal Timer
          ansible.builtin.systemd_service:
            name: tailscale_gen_cert.timer
            enabled: true
            state: "started"

        - name: Add tailscale0 to trusted firewall zone
          ansible.posix.firewalld:
            interface: tailscale0
            state: enabled
            zone: trusted
            immediate: true
            permanent: true

    - name: Setup Backups
      when: "'nobackup' not in group_names"
      vars:
        kuma_push_url: "{{ borgmatic.secrets.UPTIME_KUMA }}"
      ansible.builtin.include_tasks: files/services/backup/tasks/install.yml

    - name: Setup Central DB
      ansible.builtin.include_tasks: files/services/centraldb/tasks/install.yml

    - name: Setup Proxy
      ansible.builtin.include_tasks: files/services/proxy/tasks/install.yaml

    # - name: Setup Crowdsec
    #   ansible.builtin.include_tasks: files/services/proxy/tasks/install-crowdsec.yml

    # - name: Setup Caddy
    #   ansible.builtin.include_tasks: files/services/proxy/tasks/install-caddy.yml
