---
- name: Reboot
  hosts: coreos
  become: true
  tasks:
    - name: Bootc Upgrade
      vars:
        bootc: true
      ansible.builtin.command:
        argv:
          - bootc
          - switch
          - ghcr.io/braccae/coreos:fedora
      changed_when: bootc

    - name: Reboot systems
      ansible.builtin.reboot:
        reboot_command: 'systemctl reboot'
        reboot_timeout: 1200
