<<: !include /etc/borgmatic/common.yaml

archive_name_format: 'vaultwarden-{now}'

source_directories:
    - /var/home/{{ user }}/appdata/vaultwarden

postgresql_databases:
    - name: app_vaultwarden
      username: admin
      password: "{credential systemd centraldb_postgres}"
      format: directory
      pg_dump_command: "{root_helper} {centraldb} pg_dump"
      pg_restore_command: "{root_helper} {centraldb} pg_restore"
      psql_command: "{root_helper} {centraldb} psql"

commands:
    - before: configuration
      when:
        - create
      run:
        - "{apps_helper} systemctl --user stop vaultwarden-pod"

    - after: configuration
      when:
        - create
      run:
        - "{apps_helper} systemctl --user start vaultwarden-pod"