---
- name: Setup repositories for EL systems
  when: "'package_managed' in group_names and ansible_os_family == 'RedHat'"
  block:
    - name: Get RHEL version
      ansible.builtin.shell: set -o pipefail && rpm -E %rhel
      register: rhel_version
      changed_when: false

    - name: Get distribution
      ansible.builtin.shell: set -o pipefail && rpm --eval "%{dist}"
      register: dist
      changed_when: false

    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Install RPM Fusion repositories
      ansible.builtin.dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ rhel_version.stdout }}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ rhel_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Install OpenZFS repository
      ansible.builtin.dnf:
        name: "https://zfsonlinux.org/epel/zfs-release-2-8{{ dist.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: "https://pkgs.tailscale.com/stable/rhel/{{ rhel_version.stdout }}/tailscale.repo"
        dest: /etc/yum.repos.d/tailscale.repo
        mode: '0644'

    - name: Add Crowdsec repository
      ansible.builtin.copy:
        content: |
          [crowdsec_crowdsec]
          name=crowdsec_crowdsec
          baseurl=https://packagecloud.io/crowdsec/crowdsec/el/9/$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=
            https://packagecloud.io/crowdsec/crowdsec/gpgkey
            https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-EDE2C695EC9A5A5C.pub.gpg
            https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-C822EDD6B39954A1.pub.gpg
            https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=3600
        dest: /etc/yum.repos.d/crowdsec.repo
        mode: '0644'

    - name: Add Wazuh repository
      ansible.builtin.copy:
        content: |
          [wazuh]
          gpgcheck=1
          gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
          enabled=1
          name=EL-10 - Wazuh
          baseurl=https://packages.wazuh.com/4.x/yum/
          priority=1
        dest: /etc/yum.repos.d/wazuh.repo
        mode: '0644'

    - name: Install uv (Python package manager)
      ansible.builtin.shell: |
        set -o pipefail
        curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="/usr/bin" sh
      args:
        creates: /usr/bin/uv

    - name: Install rclone
      ansible.builtin.shell: |
        set -o pipefail
        curl https://rclone.org/install.sh | bash
      args:
        creates: /usr/bin/rclone

    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true

- name: Install required packages for non-bootc
  ansible.builtin.package:
    name:
      - qemu-guest-agent
      - just
      - tuned
      - realmd
      - sssd
      - tailscale
      - firewalld
      - sqlite
      - borgbackup
      - fuse
      - rclone
      - rsync
      - python3-psycopg2
      - xdg-user-dirs
      - python3-pip
      - git
      - tmux
    state: present
